### ISSUE TITLE
Find a source for PCRE2

### ISSUE THREAD

**Issue by sjshuck** [sjshuck/hs-pcre2#10]
Currently we have https://github.com/jwilk-mirrors/pcre2.git as a Git submodule.  It has not been updated to 10.36 which was released a few days ago.

The PCRE2 repo is Subversion.  Technically Cabal supports SVN repos, but hpack/Stack don't.  At the moment there does not seem to be a way to refer to the PCRE2 C sources online in a way that's reliable, up-to-date, and workable with CI.

**Comment by sjshuck** [comment]
@jwilk kindly updated the above repo to 10.36 on request.

**Comment by sjshuck** [comment]
Update: pcre2-1.1.3.1 is built with PCRE2 10.36.

**Comment by sjshuck** [comment]
Adding SVN support to `hpack` and then using the official upstream might be a durable solution.

**Comment by jwilk** [comment]
It looks like pcre2 has migrated to GitHub!
https://pcre.org/ reads:
> You can download the current release of the PCRE2 library from its official home on GitHub:
> https://github.com/PhilipHazel/pcre2/releases

**Comment by sjshuck** [comment]
@jwilk Thanks!

**Comment by sjshuck** [comment]
https://github.com/sjshuck/hs-pcre2/commit/de887349ed31897d9b9538b604d2017e4741d130
