### ISSUE TITLE
Support text-2.0

### ISSUE THREAD

**Issue by sjshuck** [sjshuck/hs-pcre2#22]
UTF-8 in `text` has landed.  https://hackage.haskell.org/package/text-2.0/changelog

EDIT: Current list of blockers:
- [x] #25
- [x] #26

**Comment by sjshuck** [comment]
Currently Stack builds succeed but Cabal builds do not.  https://github.com/sjshuck/hs-pcre2/commit/92531dc10acbb3b6e246889b748453474500650d

**Comment by tchoutri** [comment]
@sjshuck I'd like to help with the migration! Anything I could do to help or do you wish to handle this yourself?

**Comment by sjshuck** [comment]
@tchoutri Absolutely, help welcome!
I haven't used Github to track work before; only used Jira and Gitlab.  I'll make a task list in the first comment of all the known blockers.  ("You cannot create task list items within...issues with linked pull requests" isn't very encouraging...)

**Comment by tchoutri** [comment]
@sjshuck Wonderful. :) I have a personal stake in this with [Flora](https://github.com/flora-pm/flora-server), so please don't hesitate to share the burden!

**Comment by sjshuck** [comment]
@tchoutri Created a little list of open issues, see above.  I'd like to use `text-2` as a feature branch.  Feel free to open PRs against it.  Thanks!

**Comment by sjshuck** [comment]
Going to close this but leave #26 open.  It's a small regression.  I want this in Stackage Nightly ~just like `text-2.0` is~.
EDIT: `text-2.0` isn't in Nightly and I don't know when that's going to happen.  But regardless, we're ready for it.

**Comment by andreasabel** [comment]
Requirement `text >= 2` broke Stackage nightly.  See:
- https://github.com/commercialhaskell/stackage/issues/6593

**Comment by tchoutri** [comment]
@sjshuck Hi! Now that `text-2.0` is shipped with GHC 9.4, do you wish to enable the support? :)

**Comment by sjshuck** [comment]
@tchoutri Version 2.2+ already supports `text-2.0`.  The only place it isn't enabled is Stackage, where `pcre2` is pinned to <2.2, because GHC 9.4 isn't in either LTS or nightly yet.
If you want to try to build `pcre2` and manage dependencies yourself, [this file](https://github.com/sjshuck/hs-pcre2/blob/e364defa70f6e52c4c737659ea831f9ba2f300fb/stack.yaml) will help you.
If not, wait until `text-2.0` is included in Stackage.
