### ISSUE TITLE
Cabal builds failing

### ISSUE THREAD

**Issue by sjshuck** [sjshuck/hs-pcre2#25]
In `text-2` branch, the Cabal CI actions fail with

```
cabal.exe: Cannot test the package pcre2-2.2.0 because none of the components
are available to build: the test suite 'pcre2-test' is not available because
the solver did not find a plan that included the test suites. Force the solver
to enable this for all packages by adding the line 'tests: True' to the
'cabal.project.local' file.
```

**Comment by sjshuck** [comment]
I suspect the cause is temporary pinning of versions in `stack.yaml` and `package.yaml`.  When text 2.0 hits Stackage LTS probably this summer, those pinnings can go away.  But naturally I'd like to release 2.2.0 before then to get it in that Stackage cycle.

EDIT: Pinning `text >=2` in `package.yaml` should _not_ go away.

**Comment by tchoutri** [comment]
@sjshuck I've started a cabal build on the `text-2` branch and I am getting this:

```
<command line>: does not exist: src/c/pcre2/src/pcre2_auto_possess.c   
```

How can I fix this?

**Comment by sjshuck** [comment]
Be sure to clone submodules in addition to the `hs-pcre2` repo.

**Comment by sjshuck** [comment]
Fixed by https://github.com/sjshuck/hs-pcre2/commit/4c063adc152a1426619f95f11a32f2afd9596e3f.
